# Generated by Django 5.0.6 on 2024-07-14 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_doc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='glaccount',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upload_doc.accountcategory'),
        ),
    ]
