# Generated by Django 5.0.6 on 2024-07-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_doc', '0002_document_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='s3_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
