# Generated by Django 5.0.6 on 2024-07-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_doc', '0002_alter_glaccount_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontype',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, null=True),
        ),
    ]
