# Generated by Django 5.0.6 on 2024-08-02 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_doc', '0004_expensecategory_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='balance_and_payment',
        ),
        migrations.RemoveField(
            model_name='document',
            name='credit_card_summary',
        ),
        migrations.AddField(
            model_name='balanceandpayment',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balance_and_payment', to='upload_doc.document'),
        ),
        migrations.AddField(
            model_name='balanceandpayment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balance_and_payment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditcardsummary',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_card_summary', to='upload_doc.document'),
        ),
        migrations.AddField(
            model_name='creditcardsummary',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_card_summary', to=settings.AUTH_USER_MODEL),
        ),
    ]
